GISHELAWATI 10319046

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
TID = [['M', 'O', 'N', 'K', 'E', 'Y'],
       ['D', 'O', 'N', 'K', 'E', 'Y'],
       ['M', 'A', 'K', 'E'],
       ['M', 'U', 'C', 'K', 'Y'],
       ['C', 'O', 'O', 'K', 'I', 'E']]

In [ ]:
te = TransactionEncoder()
te_ary = te.fit(TID).transform(TID)

In [ ]:
# Konversi array numpy menjadi dataframe
df = pd.DataFrame(te_ary, columns=te.columns_)

In [ ]:
# Cari frequent itemset dengan minimum support 0.6
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)

In [ ]:
# 1. ITEM SET MENCOLOK
frequent_itemsets

    support   itemsets
0       0.8        (E)
1       1.0        (K)
2       0.6        (M)
3       0.6        (O)
4       0.6        (Y)
5       0.8     (E, K)
6       0.6     (E, O)
7       0.6     (K, M)
8       0.6     (K, O)
9       0.6     (Y, K)
10      0.6  (E, K, O)

In [ ]:
# 2. CONTOH ASOSIASI KUAT
# Cari aturan asosiasi dengan minimum confidence 0.8
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(E),(K),0.8,1.0,0.8,1.0,1.00,0.00,inf
1,(K),(E),1.0,0.8,0.8,0.8,1.00,0.00,1.0
2,(O),(E),0.6,0.8,0.6,1.0,1.25,0.12,inf
3,(M),(K),0.6,1.0,0.6,1.0,1.00,0.00,inf
4,(O),(K),0.6,1.0,0.6,1.0,1.00,0.00,inf
5,(Y),(K),0.6,1.0,0.6,1.0,1.00,0.00,inf
6,"(E, O)",(K),0.6,1.0,0.6,1.0,1.00,0.00,inf
7,"(K, O)",(E),0.6,0.8,0.6,1.0,1.25,0.12,inf
8,(O),"(E, K)",0.6,0.8,0.6,1.0,1.25,0.12,inf